apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../configs/lab-common
  - ingress-config.yaml
  - letsencrypt-config.yaml
  - cloudflare-secret.yaml

components:
  - ../../base
  - ../../base/nginx-ingress/components/issuers/letsencrypt-cloudflare
