apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/baremetal/deploy.yaml
  - ip-pool.yaml

patches:
  - path: loadbalancer-patch.yaml

replacements:
  - path: loadbalancer-ip-replace.yaml
