source:
  kind: ConfigMap
  name: nginx-ingress-config
  fieldPath: data.ip
targets:
  - select:
      kind: Service
      name: ingress-nginx-controller
    fieldPaths:
      - metadata.annotations.[kube-vip.io/loadbalancerIPs]
    options:
      create: true
