source:
  kind: ConfigMap
  name: metalkast.io/system-config
  fieldPath: data.ingress_ip
targets:
  - select:
      kind: Service
      name: ingress-nginx-controller
    fieldPaths:
      - metadata.annotations.[kube-vip.io/loadbalancerIPs]
    options:
      create: true
