source:
  kind: ConfigMap
  name: metalkast.io/cluster-version
  fieldPath: data.node_image_url
targets:
  - select:
      group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: Metal3MachineTemplate
    fieldPaths:
      - spec.template.spec.image.url
    options:
      create: true
