source:
  kind: ConfigMap
  name: metalkast.io/cluster-config
  fieldPath: data.control_plane_ip
targets:
  - select:
      kind: Service
      name: kubernetes-external
    fieldPaths:
      - metadata.annotations.[io.cilium/lb-ipam-ips]
    options:
      create: true
  - select:
      group: cilium.io
      version: v2alpha1
      kind: CiliumLoadBalancerIPPool
      name: api-server
    fieldPaths:
      - spec.blocks.[cidr=__API_SERVER_IP_PLACEHOLDER__/32].cidr
    options:
      create: true
      delimiter: "/"
      index: 0
