source:
  kind: ConfigMap
  name: k8s-cluster-config
  fieldPath: data.CONTROL_PLANE_HOSTNAME
targets:
- select:
    group: infrastructure.cluster.x-k8s.io
    version: v1beta1
    kind: Metal3Cluster
  fieldPaths:
    - spec.controlPlaneEndpoint.host
  options:
    create: true
