apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-config.yaml
  - kube-apiserver-config.yaml

components:
  - ../../base
  - ../../base/ironic/components/insecure
  - ../../base/nginx-ingress/components/issuers/self-signed
