apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cilium
  releaseName: cilium
  namespace: kube-system
  version: 1.15.3
  repo: https://helm.cilium.io/
  valuesInline:
    kubeProxyReplacement: true
    k8sServiceHost: "this need to be set but will be replaced"
    k8sServicePort: 6443
    l2announcements:
      enabled: true
    # https://docs.cilium.io/en/latest/network/l2-announcements/#sizing-client-rate-limit
    k8sClientRateLimit:
      qps: 10
      burst: 30
    ingressController:
      enabled: true
      loadbalancerMode: shared
    operator:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
    ipam:
      mode: kubernetes
    hubble:
      tls:
        auto:
          method: cronJob
      relay:
        enabled: true
        rolloutPods: true
      ui:
        enabled: true
        rolloutPods: true
        ingress:
          enabled: true
          className: cilium
          hosts:
            - &hubble_host hubble.__DOMAIN__
          tls:
            - secretName: hubble-ui-tls
              hosts:
                - *hubble_host
          annotations:
            cert-manager.io/cluster-issuer: ingress-issuer
            external-dns.alpha.kubernetes.io/hostname: *hubble_host
