#!/usr/bin/env bash
set -eEuo pipefail
shopt -s extglob

INSTALL_SCRIPTS=$(dirname -- "$0")
SCRIPT_NAME=$(basename "$0")

# env file is generated by build.sh script
ENV_FILE=${INSTALL_SCRIPTS}/.env

# https://stackoverflow.com/a/43267603
set -a # automatically export all variables
source ${ENV_FILE}
set +a


for script in ${INSTALL_SCRIPTS}/!(${SCRIPT_NAME}|${ENV_FILE}); do
    $script
done
