# apiVersion: builtin
# kind: ConfigMapGenerator
# metadata:
#   name: ironic-replacement-endpoints
# options:
#   disableNameSuffixHash: true
#   annotations:
#     config.kubernetes.io/local-config: "true"
# literals:
#   - IRONIC_CONDUCTOR_ENDPOINT=<IRONIC_IP>:80
#   - IRONIC_SERVICE_CATALOG_ENDPOINT=<IRONIC_IP>:6385
#   - IRONIC_INSPECTOR_ENDPOINT=<IRONIC_IP>:5050
# ---
apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replace-ironic-endpoints
replacements:
  - source:
      kind: ConfigMap
      name: ironic-ip
      namespace: ironic
      fieldPath: data.OS_DEFAULT__HOST
    targets:
      - select:
          kind: ConfigMap
          name: ironic-replacement-endpoints
        fieldPaths:
          - data.IRONIC_CONDUCTOR_ENDPOINT
          - data.IRONIC_SERVICE_CATALOG_ENDPOINT
          - data.IRONIC_INSPECTOR_ENDPOINT
        options:
          delimiter: ':'
          index: 0
  - source:
      kind: ConfigMap
      name: ironic-replacement-endpoints
      fieldPath: data.IRONIC_CONDUCTOR_ENDPOINT
    targets:
      - select:
          kind: ConfigMap
          name: ironic
        fieldPaths:
          - data.DEPLOY_RAMDISK_URL
          - data.DEPLOY_KERNEL_URL
        options:
          delimiter: '/'
          index: 2
  - source:
      kind: ConfigMap
      name: ironic-replacement-endpoints
      fieldPath: data.IRONIC_SERVICE_CATALOG_ENDPOINT
    targets:
      - select:
          kind: ConfigMap
          name: ironic
        fieldPaths:
          - data.IRONIC_ENDPOINT
        options:
          delimiter: '/'
          index: 2
  - source:
      kind: ConfigMap
      name: ironic-replacement-endpoints
      fieldPath: data.IRONIC_INSPECTOR_ENDPOINT
    targets:
      - select:
          kind: ConfigMap
          name: ironic
        fieldPaths:
          - data.IRONIC_INSPECTOR_ENDPOINT
        options:
          delimiter: '/'
          index: 2
# ---
# apiVersion: builtin
# kind: PatchTransformer
# metadata:
#   name: remove-ironic-replacement-endpoints
# target:
#   name: ironic-replacement-endpoints
#   kind: ConfigMap
# patch: |-
#   apiVersion: v1
#   metadata:
#     name: ironic-replacement-endpoints
#   kind: ConfigMap
#   $patch: delete
