apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: kube-vip
          env:
            - name: vip_leaseduration
              value: "30"
            - name: vip_renewdeadline
              value: "20"
            - name: vip_retryperiod
              value: "4"
