apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube-apiserver-config.yaml
  - ingress-config.yaml
  - letsencrypt-config.yaml
  - cloudflare-secret.yaml

components:
  - https://github.com/metalkast/metalkast//manifests/system/base
  - https://github.com/metalkast/metalkast//manifests/system/base/nginx-ingress/components/issuers/letsencrypt-cloudflare
