#!/bin/bash
set -euo pipefail

for i in `seq 1 3`; do
  until curl -k --silent -o /dev/null "https://192.168.122.10$i/redfish/v1"; do sleep 1; done
done

export SOPS_AGE_KEY="AGE-SECRET-KEY-15JLZDHADZ45JVZXMKSAM9U8AHE47DDK7DTJL7XNR0G27U4P9XRHQLNKUH2"

kast generate \
  manifests/cluster/deployments/dev/nodes-secrets.yaml \
  manifests/cluster/deployments/dev/nodes.yaml

kast bootstrap \
  manifests/system/deployments/dev \
  manifests/cluster/deployments/dev
