apiVersion: v1
kind: Secret
metadata:
    name: redfish-creds-k8s-nodes
    annotations:
        metalkast.io/redfish-urls: |-
            https://192.168.122.101
            https://192.168.122.102
            https://192.168.122.103
stringData:
    username: ENC[AES256_GCM,data:QI0kY2A=,iv:2j+/bN5hlQCkum4eRBRS/bsLhgL0Lpy/A3t4c6OsHVs=,tag:BG2BonEt9HuuASIS7FJSag==,type:str]
    password: ENC[AES256_GCM,data:FYN68wvofxI=,iv:WobUB1qMSqvbho5qZMC3mVztY6vNFVHXTZ9Yr4YqkHo=,tag:YWvLtJJY3fUqm6Wo+lnZMA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dk25phcnxzhkryzn7smn29wa4lhsplgvty3skzddr2w5plsh0ddq04ukv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RHJrUTAzdzhlZWNWM2lr
            dHFSc2o1dE53aTdXRldDcm9iWVdibHRueVJRCncxREpmejFESTB1d1YxQkh5c2Vu
            TUM5bmh4NXd3Yjl1SUVwcUtYYml5ME0KLS0tIG0wMS9SNitoMUkvZ0g5d2dVcWVu
            bG5GWHZkZXBHclZmREpGbjRidjgzaDAKvDAV+HePfd5UcsRm8KyxHkn4YCAJVkFK
            W3Dq8cEOE7yqWww7Uv7RxXbFO+C+3qS7tCjADEShc7cIfk+Z9QTmSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-31T17:02:21Z"
    mac: ENC[AES256_GCM,data:NhTff4mQ94+Ji0PkA6UhTLkCYaQLjp56SvQknFqifAY92EA1tt7R7ad2bjvA74l7LOboX4yfeDKj/eReK+iWZdZ0RAULxCf09kHBU1L65Z84noTwGd3wvZHDBrIWyBfe/Jp0CFBhTIqh4O64+3n/5WZFCb/0/RrtpS9lcITBJLY=,iv:vtqjeFD24XPn5EEOtmM7oPkTaDk7MmBRnHlmpqZ+wOI=,tag:Z2450yNcStAqkhw8S17vYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
