apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../configs/lab-common
  - ingress-config.yaml

components:
  - https://github.com/metalkast/metalkast//manifests/system/base
  - https://github.com/metalkast/metalkast//manifests/system/base/ironic/components/insecure
  - https://github.com/metalkast/metalkast//manifests/system/base/nginx-ingress/components/issuers/self-signed
