apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../configs/lab-common
  - ingress-config.yaml

components:
  - ../../base
  - ../../base/ironic/components/insecure
  - ../../base/nginx-ingress/components/issuers/self-signed
