---
version: "3"

services:
  lab:
    build:
      context: container-images/redfish-lab
    privileged: true
    volumes:
      - build-output:/var/www/html
    depends_on:
      image-build:
        condition: service_completed_successfully

include:
  - ../image-build/docker-compose.yaml
