# TODO: Convert to configMapGenerator when kustomize upgraded to v5.1.0+.
# Current version of kustomize runs components before configMapGenerator
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-cluster-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  CONTROL_PLANE_HOSTNAME: 192.168.123.104
