---
# TODO: Convert to configMapGenerator when kustomize upgraded to v5.1.0+.
# Current version of kustomize runs components before configMapGenerator
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-cluster-version
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  VERSION: v1.28.4
  NODE_IMAGE_URL: http://192.168.122.1/k8s-v1.28.4-ubuntu-22.04-20230719-amd64-dev/cluster-node.img
  NODE_IMAGE_CHECKSUM: http://192.168.122.1/k8s-v1.28.4-ubuntu-22.04-20230719-amd64-dev/cluster-node.img.sha256sum
