apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: KubeadmControlPlane
    patch: |-
      - op: add
        path: /spec/kubeadmConfigSpec/preKubeadmCommands/-
        value: |
          apt-get -yq update
          apt install -yq openssh-server
          systemctl enable ssh
          sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          systemctl restart ssh
          useradd debug -m -p $(openssl passwd debug) -G sudo
          echo 'debug ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/debug
