---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: control-plane
spec:
  serviceSelector:
    matchLabels:
      component: apiserver
      provider: kubernetes
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
spec:
  serviceSelector:
    matchExpressions:
      - key: component
        operator: NotIn
        values: [apiserver]
      - key: provider
        operator: NotIn
        values: [kubernetes]
  loadBalancerIPs: true
