source:
  kind: ConfigMap
  name: metalkast.io/system-config
  fieldPath: data.ingress_ip
targets:
  - select:
      kind: Service
      name: cilium-ingress
      namespace: kube-system
    fieldPaths:
      - metadata.annotations.[io.cilium/lb-ipam-ips]
    options:
      create: true
  - select:
      group: cilium.io
      version: v2alpha1
      kind: CiliumLoadBalancerIPPool
    fieldPaths:
      - spec.blocks.[cidr=__INGRESS_IP_PLACEHOLDER__/32].cidr
    options:
      create: true
      delimiter: "/"
      index: 0
