apiVersion: v1
kind: Secret
metadata:
    name: redfish-creds-k8s-nodes
    annotations:
        metalkast.io/redfish-urls: |-
            https://192.168.122.101
            https://192.168.122.102
            https://192.168.122.103
data:
    username: ENC[AES256_GCM,data:FLKok0nSVCE=,iv:hvwgyk48JLBeAT9bUaJcdhaaLD8yVRAnKYA1IPnYNI0=,tag:2HkUei3vINmeS3R+1k0wfQ==,type:str]
    password: ENC[AES256_GCM,data:K9BauC1/p9eCsHHL,iv:sfMXRS/+D+ZVtpMK4YHeYXnD8NwmfzupstwQFzQj0No=,tag:Vc3+uvItiSU+xBqjRkx0fQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dk25phcnxzhkryzn7smn29wa4lhsplgvty3skzddr2w5plsh0ddq04ukv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RHJrUTAzdzhlZWNWM2lr
            dHFSc2o1dE53aTdXRldDcm9iWVdibHRueVJRCncxREpmejFESTB1d1YxQkh5c2Vu
            TUM5bmh4NXd3Yjl1SUVwcUtYYml5ME0KLS0tIG0wMS9SNitoMUkvZ0g5d2dVcWVu
            bG5GWHZkZXBHclZmREpGbjRidjgzaDAKvDAV+HePfd5UcsRm8KyxHkn4YCAJVkFK
            W3Dq8cEOE7yqWww7Uv7RxXbFO+C+3qS7tCjADEShc7cIfk+Z9QTmSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-27T20:00:02Z"
    mac: ENC[AES256_GCM,data:iE5v36JugQgA2MqwaG018G3LRUu5EcMsRrimsDsx+fwhsXZpJ3hEq4fJd4SFbTBg21rfOLKT7KHDVf9iO9ISj476NYnItAuStKOGCYKNZaJzwKayonSCJNa54mtuiKrf+HD2haHm65SjvHRcAqlkynafg2JQmRJocQOJU+oHbS8=,iv:LCFqUyzmUjVK1DxueByXwQhLYhKmQUqSfVSat8KmtHg=,tag:zy8sBioWpFwg80Nzt0CUDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
